### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 83 (SessionNotCreated)

### ISSUE THREAD

**Issue by dilshank90** [rosolko/WebDriverManager.Net#93] opened 2020-09-07 04:50 UTC
**Description of the problem :**
I am using webdrivermanager to manage chromedriver.exe. When I execute the code the following message was displayed in the console
Error Message:
    _OneTimeSetUp: System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 83 (SessionNotCreated)_

**Browser and version :**
Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Operating** system :
Windows 10 Enterprise

**WebDriverManager version :**
2.9.3

**Comment by Dimitvp** [comment] 2020-09-10 09:47
It seems to me that this is
Duplicate of #90

**Comment by dilshank90** [comment] 2020-09-10 10:03
> 
> 
> It seems to me that this is
> Duplicate of #90
 
I used webdriver manager for my implementation from the beginning and it worked fine. Suddenly, my chrome browser got updated to the latest version and my test scripts started to fail due to this issue. Could you please tell me how to solve this issue?

**Comment by dilshank90** [comment] 2020-09-10 10:57
@rosolko Any thoughts?

**Closed** 2020-09-17 12:53 UTC
Labels: bug
