### ISSUE TITLE
WebDriverManager not working in VS 2022 C#

### ISSUE THREAD

**Issue by DirkDiggler77** [rosolko/WebDriverManager.Net#227] opened 2023-01-14 01:33 UTC
Hello! 

I am trying to get WebDriverManager working in my VS project BUT it doesn't seem to working.
My Browser is Chrome 109 and my ChromeDriver is 107. I was under the impression when using WebDriverManager
that if they were out of sync WebDriverManager would still allow them to run by having the project use the most current version of ChromeDriver. Is this not the case? Any additional help would be greatly appreciated.

Thanks
Dirk!

// Error
 Test
   Source: DAM_Basics.cs line 25
   Duration: 2.1 sec

  Message: 
System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 109.0.5414.75 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeOptions options)
ChromeDriver.ctor()
Tests.SetUp() line 19

// Script 

using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;
using WebDriverManager.Helpers;

namespace Test
{
    [TestFixture]
    public class Tests
    {
        private IWebDriver _webDriver;

        [SetUp]
        public void SetUp()
        {
            new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);
            _webDriver = new ChromeDriver();
        }

        [Test]
        public void Test()
        {
            _webDriver.Navigate().GoToUrl("https://www.google.com");
            Assert.True(_webDriver.Title.Contains("Google"));
        }
    }
}

**Comment by khalidifq** [comment] 2023-02-17 09:42
Same issue is experienced by me on VS2022. Any updates on how to resolve this?

**Comment by JohnnyNgo** [comment] 2023-02-26 11:34
Same issue VS2022

**Comment by JohnnyNgo** [comment] 2023-02-26 11:42
> Same issue is experienced by me on VS2022. Any updates on how to resolve this?



> Hello!
> 
> I am trying to get WebDriverManager working in my VS project BUT it doesn't seem to working. My Browser is Chrome 109 and my ChromeDriver is 107. I was under the impression when using WebDriverManager that if they were out of sync WebDriverManager would still allow them to run by having the project use the most current version of ChromeDriver. Is this not the case? Any additional help would be greatly appreciated.
> 
> Thanks Dirk!
> 
> // Error  Test  Source: DAM_Basics.cs line 25  Duration: 2.1 sec
> 
> Message:  System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 107 Current browser version is 109.0.5414.75 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
> 
> Stack Trace:  WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute) WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) WebDriver.StartSession(ICapabilities desiredCapabilities) WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities) ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout) ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout) ChromeDriver.ctor(ChromeOptions options) ChromeDriver.ctor() Tests.SetUp() line 19
> 
> // Script
> 
> using NUnit.Framework; using OpenQA.Selenium; using OpenQA.Selenium.Chrome; using WebDriverManager; using WebDriverManager.DriverConfigs.Impl; using WebDriverManager.Helpers;
> 
> namespace Test { [TestFixture] public class Tests { private IWebDriver _webDriver;
> 
> ```
>     [SetUp]
>     public void SetUp()
>     {
>         new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);
>         _webDriver = new ChromeDriver();
>     }
> 
> 
> 
>     [Test]
>     public void Test()
>     {
>         _webDriver.Navigate().GoToUrl("https://www.google.com");
>         Assert.True(_webDriver.Title.Contains("Google"));
>     }
> }
> ```
> 
> }

brothers, i found a solution for now
`			string file = new DriverManager().SetUpDriver(new ChromeConfig());
			string dir = Path.GetDirectoryName(file); // Redundant!
			IWebDriver driver = new ChromeDriver(dir);`

**Comment by DirkDiggler77** [comment] 2023-02-27 22:42
@JohnnyNgo Will give this a try!

Cheers
Dirk

**Comment by AllOfUs9898** [comment] 2023-03-16 17:38
@JohnnyNgo Thank you for the solution. Just tried it and it works!

**Comment by matthewdavidjeffery** [comment] 2023-03-22 21:59
This also worked for me.

**Comment by Sahnreis** [comment] 2023-04-19 13:41
this issue is a duplicate of #209

**Comment by samueltian666** [comment] 2023-04-30 12:29
the best:
new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);
ChromeDriver driver = new();
That's it!

**Comment by dwiggins5091** [comment] 2023-06-10 00:14
VersionResolveStrategy.MatchingBrowser doesnt work as expected... regardless of the Visual Studio version that a developer is using on their machine

**Comment by Abhijith1190** [comment] 2023-06-12 13:08
@dwiggins5091 how do we overcome this issue? Please help

**Comment by ms6073** [comment] 2023-07-27 19:45
> @dwiggins5091 how do we overcome this issue? Please help

Take a look at [issue 253](https://github.com/rosolko/WebDriverManager.Net/issues/253) for more context regarding the cause of the issue.

**Closed** 2023-09-18 14:51 UTC
