### ISSUE TITLE
[🐛 Bug]: Selenium4, CSharp & WebDriverManager is not downloading the latest version of EdgeDriver and throwing error

### ISSUE THREAD

**Issue by svadivel0006** [rosolko/WebDriverManager.Net#198] opened 2022-07-12 19:27 UTC
### **Screenshots:**

**_Error Details:_**
![image](https://user-images.githubusercontent.com/85741928/178575909-4e287304-2696-463f-97d0-02989d303256.png)

**_EdgeDriver latest version not downloaded details:_**
![image](https://user-images.githubusercontent.com/85741928/178575994-95e0819d-4f77-4d22-9cae-bf8416c29796.png)

**_Installed Edge Browser version:_**
![image](https://user-images.githubusercontent.com/85741928/178576129-90fa6ff2-7c1d-4c79-82b2-3fbde3f14fb3.png)

**Comment by gburghardt** [comment] 2022-07-12 20:23
This appears to be a duplicate of #168.

**Closed** 2022-07-13 07:15 UTC

**Comment by gburghardt** [comment] 2022-07-13 20:51
We are still getting this error with Edge v103.0.1264.49 installed on our work laptops.
